/**
 * CR_OODA_GROUNDED_EVAL_HARNESS_V2 — pass-k, admission-gate, distortion-index.
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { listAdmissionCases, runAdmissionGate, saveAdmissionCase } from "./admission-gate.js";
import {
  appendDistortionSample,
  computeDistortion,
  readDistortionHistory,
} from "./distortion-index.js";
import { runPassK } from "./pass-k.js";
import type { ActualOutcome, AdmissionCase, DistortionSample, PolicyProposal } from "./types.js";

const mockCase = (
  id: string,
  priorOutcome: AdmissionCase["priorOutcome"] = "success",
): AdmissionCase => ({
  id,
  label: id,
  fixture: {
    observation: "test",
    knowledge: {} as unknown as AdmissionCase["fixture"]["knowledge"],
    priorities: {} as unknown as AdmissionCase["fixture"]["priorities"],
  },
  expected: {
    actionId: id,
    description: "",
    successSignal: "",
    failureSignal: "",
    domain: "x",
  },
  priorOutcome,
  capturedAt: new Date().toISOString(),
});

const mockProposal: PolicyProposal = {
  id: "p1",
  timestamp: "",
  rule: "",
  proposal: "",
  reasoning: "",
  evidence: [],
  status: "pending",
  category: "policy",
  confidence: 0.9,
  autoGenerated: false,
};

const alwaysSuccess = async (): Promise<ActualOutcome> => ({
  source: "tool_result",
  success: true,
  toolName: "t",
  summary: "",
});
const alwaysFail = async (): Promise<ActualOutcome> => ({
  source: "tool_result",
  success: false,
  toolName: "t",
  summary: "",
});

describe("runPassK", () => {
  it("computes pass^k for trivially-passing cases", async () => {
    const cases = [mockCase("a"), mockCase("b"), mockCase("c")];
    const result = await runPassK(cases, alwaysSuccess, {
      kValues: [1, 2, 4, 8],
      caseIds: [],
      caseTimeoutMs: 5000,
    });
    expect(result.passRates[1]).toBe(1);
    expect(result.passRates[8]).toBe(1);
  });

  it("drops to 0 for always-failing cases", async () => {
    const cases = [mockCase("a"), mockCase("b")];
    const result = await runPassK(cases, alwaysFail, {
      kValues: [1, 2, 8],
      caseIds: [],
      caseTimeoutMs: 5000,
    });
    expect(result.passRates[1]).toBe(0);
    expect(result.passRates[8]).toBe(0);
  });

  it("is monotone decreasing in k for flaky cases", async () => {
    let count = 0;
    const halfPass = async (): Promise<ActualOutcome> => ({
      source: "tool_result",
      success: count++ % 2 === 0,
      toolName: "t",
      summary: "",
    });
    const cases = [mockCase("a"), mockCase("b")];
    const result = await runPassK(cases, halfPass, {
      kValues: [1, 2, 4],
      caseIds: [],
      caseTimeoutMs: 5000,
    });
    expect(result.passRates[1]).toBeGreaterThanOrEqual(result.passRates[2]);
    expect(result.passRates[2]).toBeGreaterThanOrEqual(result.passRates[4]);
  });
});

describe("runAdmissionGate", () => {
  it("falls open when corpus is below bootstrap threshold", async () => {
    const cases = [mockCase("a"), mockCase("b")];
    const report = await runAdmissionGate(mockProposal, cases, alwaysFail, {
      minCasesForGate: 5,
    });
    expect(report.admit).toBe(true);
    expect(report.admitReason).toContain("no_corpus_bootstrap");
  });

  it("admits when all cases pass at floor 0.60", async () => {
    const cases = [mockCase("a"), mockCase("b"), mockCase("c"), mockCase("d"), mockCase("e")];
    const report = await runAdmissionGate(mockProposal, cases, alwaysSuccess);
    expect(report.admit).toBe(true);
    expect(report.passRate).toBe(1);
  });

  it("rejects on regression against prior-success case", async () => {
    const cases = [mockCase("a"), mockCase("b"), mockCase("c"), mockCase("d"), mockCase("e")];
    const report = await runAdmissionGate(mockProposal, cases, alwaysFail);
    expect(report.admit).toBe(false);
    expect(report.admitReason).toContain("regression_on_prior_success_case");
  });

  it("rejects on pass rate below floor without regression", async () => {
    const cases = [
      mockCase("a", "failure"),
      mockCase("b", "failure"),
      mockCase("c", "failure"),
      mockCase("d", "failure"),
      mockCase("e", "failure"),
    ];
    const report = await runAdmissionGate(mockProposal, cases, alwaysFail);
    expect(report.admit).toBe(false);
    expect(report.admitReason).toContain("pass_rate");
  });
});

describe("admission corpus I/O", () => {
  let tmpDir: string;
  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "ooda-admission-"));
  });
  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it("saveAdmissionCase + listAdmissionCases roundtrip", () => {
    saveAdmissionCase(tmpDir, mockCase("c1"));
    saveAdmissionCase(tmpDir, mockCase("c2"));
    const cases = listAdmissionCases(tmpDir);
    expect(cases.map((c) => c.id).sort()).toEqual(["c1", "c2"]);
  });

  it("listAdmissionCases returns empty when no corpus exists", () => {
    expect(listAdmissionCases(tmpDir)).toEqual([]);
  });
});

describe("distortion-index", () => {
  let tmpDir: string;
  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "ooda-distortion-"));
  });
  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it("insufficient_data with no samples", () => {
    const reading = computeDistortion([], { days: 30, minSamples: 5 });
    expect(reading.regime).toBe("insufficient_data");
  });

  it("healthy regime when grounded tracks measured", () => {
    const samples: DistortionSample[] = [];
    const now = Date.now();
    for (let i = 0; i < 10; i++) {
      samples.push({
        domain: "x",
        timestamp: now - (10 - i) * 24 * 3600 * 1000,
        measured: 0.7 + i * 0.02,
        grounded: 0.7 + i * 0.02,
        approvalCount: 2,
        overrideCount: 1,
      });
    }
    const reading = computeDistortion(samples, { days: 30, minSamples: 5 });
    expect(reading.regime).toBe("healthy");
  });

  it("goodhart_warning when measured rises while grounded stagnates", () => {
    const samples: DistortionSample[] = [];
    const now = Date.now();
    for (let i = 0; i < 10; i++) {
      samples.push({
        domain: "x",
        timestamp: now - (10 - i) * 24 * 3600 * 1000,
        measured: 0.3 + i * 0.06, // climbs from 0.3 to 0.84
        grounded: 0.4, // flat
        approvalCount: 3,
        overrideCount: 1,
      });
    }
    const reading = computeDistortion(samples, { days: 30, minSamples: 5 });
    expect(reading.regime).toBe("goodhart_warning");
    expect(reading.goodhartIndex).toBeGreaterThan(0.2);
  });

  it("campbell_suspected when grounded reverses while approval stays positive", () => {
    const samples: DistortionSample[] = [];
    const now = Date.now();
    for (let i = 0; i < 10; i++) {
      samples.push({
        domain: "x",
        timestamp: now - (10 - i) * 24 * 3600 * 1000,
        measured: 0.8,
        grounded: 0.8 - i * 0.08, // drops from 0.8 to 0.08
        approvalCount: 5,
        overrideCount: 0,
      });
    }
    const reading = computeDistortion(samples, { days: 30, minSamples: 5 });
    expect(reading.regime).toBe("campbell_suspected");
    expect(reading.campbellIndex).toBeGreaterThan(0.2);
  });

  it("append + read distortion history roundtrip", () => {
    appendDistortionSample(tmpDir, {
      domain: "y",
      timestamp: Date.now(),
      measured: 0.5,
      grounded: 0.5,
      approvalCount: 1,
      overrideCount: 0,
    });
    const rows = readDistortionHistory(tmpDir);
    expect(rows).toHaveLength(1);
    expect(rows[0].domain).toBe("y");
  });
});
