/**
 * Policy Proposal Storage
 *
 * Manages `.policy-proposals.json` — the append-only store for
 * Meta-Reviewer suggestions that require user approval before
 * modifying SOUL.md or other policy files.
 *
 * The Meta-Reviewer never auto-updates SOUL.md.
 */

import fs from "node:fs";
import path from "node:path";
import type { PolicyProposal } from "./types.js";

const PROPOSALS_FILENAME = ".policy-proposals.json";

// ============================================================================
// Path Resolution
// ============================================================================

export function proposalsPath(workspacePath: string): string {
  return path.join(workspacePath, PROPOSALS_FILENAME);
}

// ============================================================================
// Read / Write
// ============================================================================

/**
 * Read all policy proposals from disk.
 * Returns an empty array if the file doesn't exist.
 */
export function getProposals(workspacePath: string): PolicyProposal[] {
  const filePath = proposalsPath(workspacePath);

  if (!fs.existsSync(filePath)) {
    return [];
  }

  const raw = fs.readFileSync(filePath, "utf-8");
  const parsed = JSON.parse(raw);

  if (!Array.isArray(parsed)) {
    throw new Error("Invalid .policy-proposals.json: expected an array");
  }

  // Migrate legacy proposals that predate category/confidence/autoGenerated fields
  return (parsed as PolicyProposal[]).map((p) => ({
    category: "policy" as const,
    confidence: 1.0,
    autoGenerated: false,
    ...p,
  }));
}

/**
 * Write proposals to disk, replacing the current file.
 */
function writeProposals(workspacePath: string, proposals: PolicyProposal[]): void {
  const filePath = proposalsPath(workspacePath);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(proposals, null, 2) + "\n", "utf-8");
}

// ============================================================================
// Operations
// ============================================================================

/**
 * Append a new policy proposal. Returns the full proposal object.
 */
export function addProposal(
  workspacePath: string,
  proposal: Omit<PolicyProposal, "status">,
): PolicyProposal {
  const proposals = getProposals(workspacePath);

  const full: PolicyProposal = {
    ...proposal,
    status: "pending",
  };

  proposals.push(full);
  writeProposals(workspacePath, proposals);
  return full;
}

/**
 * Get all pending proposals.
 */
export function getPendingProposals(workspacePath: string): PolicyProposal[] {
  return getProposals(workspacePath).filter((p) => p.status === "pending");
}

/**
 * Update the status of a proposal by ID.
 * Returns the updated proposal or null if not found.
 */
export function updateProposalStatus(
  workspacePath: string,
  proposalId: string,
  status: "approved" | "rejected",
): PolicyProposal | null {
  const proposals = getProposals(workspacePath);
  const proposal = proposals.find((p) => p.id === proposalId);

  if (!proposal) return null;

  proposal.status = status;
  writeProposals(workspacePath, proposals);
  return proposal;
}

/**
 * Count pending proposals (for preamble notification).
 */
export function countPending(workspacePath: string): number {
  return getPendingProposals(workspacePath).length;
}

// ============================================================================
// Archivist Proposal Generation
// ============================================================================

/** A proposal candidate produced by the Archivist second-pass model call. */
export interface ProposalCandidate {
  category: "project" | "workflow" | "technical";
  rule: string;
  proposal: string;
  reasoning: string;
  evidence: string[];
  confidence: number;
}

/**
 * Word-overlap ratio for semantic dedup of proposal strings.
 * Returns 0.0–1.0; values >= threshold indicate near-duplicates.
 */
function overlapRatio(a: string, b: string): number {
  const wordsA = new Set(a.toLowerCase().split(/\W+/).filter(Boolean));
  const wordsB = new Set(b.toLowerCase().split(/\W+/).filter(Boolean));
  const intersection = [...wordsA].filter((w) => wordsB.has(w)).length;
  return intersection / Math.max(wordsA.size, wordsB.size, 1);
}

/**
 * Check whether a candidate proposal is semantically similar to an existing
 * pending proposal (word overlap >= threshold).
 */
export function isDuplicateProposal(
  candidate: string,
  existing: PolicyProposal[],
  threshold = 0.5,
): boolean {
  return existing
    .filter((p) => p.status === "pending")
    .some((p) => overlapRatio(candidate, p.proposal) >= threshold);
}

/**
 * Add Archivist-generated proposals to the store.
 * Applies confidence threshold (>= 0.6), semantic dedup, and a 5-proposal cap.
 * Returns the number of proposals actually added.
 */
export function addArchivistProposals(
  workspacePath: string,
  candidates: ProposalCandidate[],
): number {
  const existing = getProposals(workspacePath);
  const pendingCount = existing.filter((p) => p.status === "pending").length;

  if (pendingCount >= 5) return 0;

  let added = 0;
  const now = new Date().toISOString();

  for (const c of candidates) {
    if (pendingCount + added >= 5) break;
    if (c.confidence < 0.6) continue;
    if (isDuplicateProposal(c.proposal, existing)) continue;

    const newProposal: PolicyProposal = {
      id: `archivist-${Date.now()}-${added}`,
      timestamp: now,
      rule: c.rule,
      proposal: c.proposal,
      reasoning: c.reasoning,
      evidence: c.evidence,
      status: "pending",
      category: c.category,
      confidence: c.confidence,
      autoGenerated: true,
    };

    existing.push(newProposal);
    added++;
  }

  if (added > 0) {
    writeProposals(workspacePath, existing);
  }

  return added;
}
